name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # Version of PostgreSQL to use
        postgresql version: 10 # optional, default is latest
        # POSTGRES_DB - name for the default database that is created
        postgresql db: runa_access_control_test # optional, default is 
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: global_production # optional, default is 
        # POSTGRES_PASSWORD - superuser password
        postgresql password: lenovo # optional, default is 
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
    - name: Create database
      - run: |
        rake db:create db:migrate RAILS_ENV=test
    - name: Run test
      - run: |
        bundle exec rspec
